/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 generator.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Machine(props) {
  const { nodes, materials } = useGLTF('/generator-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 2.96, -0.13]} scale={3.21}>
          <group position={[0, 2.96, -0.13]}>
            <mesh geometry={nodes.Cylinder_3.geometry} material={materials['default']} position={[76.44, -21.82, 17.01]} rotation={[0, -0.01, Math.PI / 2]} />
            <mesh geometry={nodes.Cylinder_2.geometry} material={materials['default']} position={[44.04, -22, 16.63]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.Rectangle_5.geometry} material={materials['default']} position={[-34.96, -11.92, 58.31]} />
            <mesh geometry={nodes.Rectangle_4.geometry} material={materials['default']} position={[-38.46, -5.14, 58.31]} />
            <mesh geometry={nodes.Rectangle_3.geometry} material={materials['default']} position={[-34.46, 17.65, 58.31]} />
            <mesh geometry={nodes.Rectangle_9.geometry} material={materials['default']} position={[53.49, -20.82, 17.34]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Rectangle_8.geometry} material={materials['default']} position={[3.77, -35.07, 55.13]} />
            <mesh geometry={nodes.Rectangle_7.geometry} material={materials['default']} position={[-18.18, -35.07, 55.13]} />
            <mesh geometry={nodes.Rectangle_6.geometry} material={materials['default']} position={[-40.12, -34.07, 55.13]} />
            <mesh geometry={nodes.Rectangle_2.geometry} material={materials['default']} position={[-34.46, 7.18, 56.39]} />
            <mesh geometry={nodes.Cube_2.geometry} material={materials['default']} position={[-0.69, 56.09, -1.41]} scale={0.74} />
            <mesh geometry={nodes.Cube.geometry} material={materials['default']} position={[-0.69, -0.53, -1.41]} scale={0.78} />
          </group>
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.15, 0.45, 0.34]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[0, 0, 1000]} />
      </group>
    </group>
  )
}

useGLTF.preload('/generator-transformed.glb')
